version: '3'
services:
    web:
        image: openjdk:15
        build: ./opina-componentes/.
        expose:
         - 8443
        depends_on:
         - db
         - si
        restart: always

    si:
        image: openjdk:15
        build: ./servicio-interno/.
        ports:
         - 9000:9000
        restart: always

    db:
        image: mysql/mysql-server:latest
        ports:
         - 3306:3306
        environment:
         - MYSQL_ROOT_PASSWORD=password

    nginx:
        image: nginx:latest
        volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
         - web
        ports:
         - 4000:4000