version: '3'
services:

    web:
        image: openjdk:latest
        volumes:
         - "./opina-componentes/opina-componentes-1.0-RELEASE.jar:/opina-componentes.jar"
        environment:
         - SPRING_DATASOURCE_URL=jdbc:mysql://db/opinacomponentes
         - VIRTUAL_HOST=opinacomponentes.com,www.opinacomponentes.com
         - LETSENCRYPT_HOST=opinacomponentes.com,www.opinacomponentes.com
         - LETSENCRYPT_EMAIL=victor@email.com
        command: "java -jar /opina-componentes.jar"
        expose:
         - 8443
        links:
         - db
         - si
        restart: always

    si:
        image: openjdk:latest
        volumes:
         - "./servicio-interno/oc-servicio-interno-1.0-RELEASE.jar:/oc-servicio-interno.jar"
        command: "java -jar /oc-servicio-interno.jar"
        ports:
         - 9000:9000
        restart: always

    db:
        image: mysql/mysql-server:latest
        ports:
         - 3306:3306
        environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=opinacomponentes
         - MYSQL_ROOT_HOST=%

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
         - /Usuarios/victo/git/varios/1/certs:/etc/nginx/certs:rw
         - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
         - nginx-proxy:rw

    nginx-proxy:
        image: jwilder/nginx-proxy
        volumes:
         -  /var/run/docker.sock:/tmp/docker.sock:ro
         -  /Usuarios/victo/git/varios/1/certs:/etc/nginx/certs:ro
         -  /etc/nginx/vhost.d
         -  /usr/share/nginx/html
        ports:
         - 8443:8443
        labels:
         - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
        restart: always
